FIND_PATH(SDL2_TTF_INCLUDE_DIR SDL_ttf.h
    HINTS
    ENV SDL2TTFDIR
    ENV SDL2DIR
    PATH_SUFFIXES SDL2
    include/SDL2 include
    PATHS ${SDL2_TTF_PATH}
)

IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(VC_LIB_PATH_SUFFIX lib/x64)
ELSE()
    SET(VC_LIB_PATH_SUFFIX lib/x86)
ENDIF()

FIND_LIBRARY(SDL2_TTF_LIBRARY
    NAMES SDL2_ttf
    HINTS
    ENV SDL2TTFDIR
    ENV SDL2DIR
    PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
    PATHS ${SDL2_TTF_PATH}
)

IF(SDL2_TTF_INCLUDE_DIR AND EXISTS "${SDL2_TTF_INCLUDE_DIR}/SDL_ttf.h")
    FILE(STRINGS "${SDL2_TTF_INCLUDE_DIR}/SDL_ttf.h" SDL2_TTF_VERSION_MAJOR_LINE REGEX "^#define[ \t]+SDL_TTF_MAJOR_VERSION[ \t]+[0-9]+$")
    FILE(STRINGS "${SDL2_TTF_INCLUDE_DIR}/SDL_ttf.h" SDL2_TTF_VERSION_MINOR_LINE REGEX "^#define[ \t]+SDL_TTF_MINOR_VERSION[ \t]+[0-9]+$")
    FILE(STRINGS "${SDL2_TTF_INCLUDE_DIR}/SDL_ttf.h" SDL2_TTF_VERSION_PATCH_LINE REGEX "^#define[ \t]+SDL_TTF_PATCHLEVEL[ \t]+[0-9]+$")
    STRING(REGEX REPLACE "^#define[ \t]+SDL_TTF_MAJOR_VERSION[ \t]+([0-9]+)$" "\\1" SDL2_TTF_VERSION_MAJOR "${SDL2_TTF_VERSION_MAJOR_LINE}")
    STRING(REGEX REPLACE "^#define[ \t]+SDL_TTF_MINOR_VERSION[ \t]+([0-9]+)$" "\\1" SDL2_TTF_VERSION_MINOR "${SDL2_TTF_VERSION_MINOR_LINE}")
    STRING(REGEX REPLACE "^#define[ \t]+SDL_TTF_PATCHLEVEL[ \t]+([0-9]+)$" "\\1" SDL2_TTF_VERSION_PATCH "${SDL2_TTF_VERSION_PATCH_LINE}")
    SET(SDL2_TTF_VERSION_STRING ${SDL2_TTF_VERSION_MAJOR}.${SDL2_TTF_VERSION_MINOR}.${SDL2_TTF_VERSION_PATCH})
    UNSET(SDL2_TTF_VERSION_MAJOR_LINE)
    UNSET(SDL2_TTF_VERSION_MINOR_LINE)
    UNSET(SDL2_TTF_VERSION_PATCH_LINE)
    UNSET(SDL2_TTF_VERSION_MAJOR)
    UNSET(SDL2_TTF_VERSION_MINOR)
    UNSET(SDL2_TTF_VERSION_PATCH)
ENDIF()

SET(SDL2_TTF_LIBRARIES ${SDL2_TTF_LIBRARY})
SET(SDL2_TTF_INCLUDE_DIRS ${SDL2_TTF_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf
    REQUIRED_VARS SDL2_TTF_LIBRARIES SDL2_TTF_INCLUDE_DIRS
    VERSION_VAR SDL2_TTF_VERSION_STRING)

SET(SDLTTF_LIBRARY ${SDL2_TTF_LIBRARIES})
SET(SDLTTF_INCLUDE_DIR ${SDL2_TTF_INCLUDE_DIRS})
SET(SDLTTF_FOUND ${SDL2_TTF_FOUND})

